### PR TITLE
support exporting TLS secrets in mock

### PR DESCRIPTION
**Pull request by enzoc4**
No one really requested this, and I'm not sure if it's worth it, but I like to use wireshark for troubleshooting.

This can be used like this: https://wiki.wireshark.org/TLS#using-the-pre-master-secret

I'm using the vitup binary directly though, using this feature with docker may require some extra configuration, in order to be able to extract the file from the container (setting up a volume?) to provide it to wireshark.

What follows is just the commit message, just leaving it here again since it adds a bit more info.

>This can be done by setting the environment variable SSLKEYLOGFILE as
supported by rustls and other common tls implementations.

>This is disabled by default in rustls, since of course it can become a
vulnerability to log session secrets, but it's useful for
troubleshooting since it can be used in wireshark (as long as you
capture the handshake, I think), and the mock is used for testing
purposes only anyway.

>Unfortunately, warp doesn't expose the setting to configure this on the
inner rustls, and from what I gathered from some discussions in the
repo, I don't think it's intended, since they offer `warp::service` for
these kind of things, so I used that directly with hyper. This is a bit
more involved, but I don't think it's overly complex, and I didn't find
an easier way anyway.

### CODE REVIEW

**Comment by dkijania** [comment]
Hey @enzoc4, if i understand correctly one of the problem is that we need to provide cert files as arguments to vitup, and it could be problematic for docker env. I bumped into same problem when removing http endpoint in vitup (as it is not used anymore by android impl of voting app). I wanted https certs (server.key and ca.crt) to be treated as project resources and automatically available in the code without passing it through command line. I learnt that this is possible using simple: https://doc.rust-lang.org/std/macro.include_str.html, like below:

```
   server_crt_content: include_str!("../../resources/tls/server.crt").to_string(),
   server_key_content: include_str!("../../resources/tls/server.key").to_string(),
```

Looking at your changes it can be useful. But  I don't really know if when wireshark is introduced in this picture, before or after you run vitup. If after, then we can just dump this file into local deployment folder (and , if used from docker, just map internal docker fs to host folder, which gives access to that file from host).

Agree that vitup mock is used purely for testing and we are keeping self-signed certs in repo, so we shouldn't care about secrets leakage

**Comment by enzoc4** [comment]
> Looking at your changes it can be useful. But I don't really know if when wireshark is introduced in this picture, before or after you run vitup. If after, then we can just dump this file into local deployment folder (and , if used from docker, just map internal docker fs to host folder, which gives access to that file from host).

You need to run it before to capture the whole thing. Not necessarily before running vitup, just running it before the first app request is fine, but it may be easier to just capture everything since the app does requests in the background. 

If you don't have the file yet you can still save the packet capture, and decrypt it later when you get it. But if the file is available from the start then you can look at the traffic while you try things, so it's a bit nicer. So ideally it would have to be a in a directory available from the host.

>Agree that vitup mock is used purely for testing and we are keeping self-signed certs in repo, so we shouldn't care about secrets leakage

And it's still opt-in, since you need to set the environment variable to a valid directory path.

> if i understand correctly one of the problem is that we need to provide cert files as arguments to vitup, and it could be problematic for docker env. I bumped into same problem when removing http endpoint in vitup (as it is not used anymore by android impl of voting app). I wanted https certs (server.key and ca.crt) to be treated as project resources and automatically available in the code without passing it through command line. I learnt that this is possible using simple: https://doc.rust-lang.org/std/macro.include_str.html, like below:

I don't understand this part, actually. I don't think I changed the behavior of this. We can certainly inline the certs in the binary if you want, but I'm not sure how is that related to this.

**Comment by dkijania** [comment]
> I don't understand this part, actually. I don't think I changed the behavior of this. We can certainly inline the certs in the binary if you want, but I'm not sure how is that related to this.

Oh yes, sorry, I became too greedy and wanted to also wanted to get rid of those input files: 
https://github.com/input-output-hk/vit-testing/pull/174/files#diff-92440869a19ac9b45f7bd18ff9e8d2efad530ed50f4c154808b3c7e66f9de10eR459

So my remark was not related to change. I just haven't fully understand wireshark sniffing procedure. After you explained it in next comment, it was clear that it should not be in the scope of those changes. It was just unrelated note. Sorry for confuson

**Comment by enzoc4** [comment]
I mean, I don't mind changing that here, I was just not sure what was the problem, since warp was also reading them from the fs. 

But I think your point is that with this change it's now possible to avoid reading them, since warp requires a path, but now we don't have that restriction anymore.

I don't mind changing the file read for `include_str!` if you want (or maybe `include_bytes!`, actually). It would still need to be parsed at runtime, of course, but if the problem is only having to pass a path through the cli then it should be enough.

**Comment by dkijania** [comment]
Yes, exactly that was my point. I think, let's do it in other pr. We can also refactor migration scripts for vit-servicing-station there

**Comment by dkijania** [comment]
Rebased with newest main

**Comment by dkijania** [comment]
Thanks @enzoc4 for this change!

**Pull request merged**
