### PR TITLE
add challenge type to proposal endpoints

### PR DESCRIPTION
**Pull request by cameron1024**
returns `FullProposalInfo` from the relevant endpoints, which includes the `challenge_type` field

### CODE REVIEW

**Comment by minikin** [comment]
LGTM

Ps: Do we need to make all tests pass for this repo?

**Review by Mr-Leshiy — APPROVED** [review]

**Comment by Mr-Leshiy** [comment]
>Ps: Do we need to make all tests pass for this repo?
I think we should ask @dkijania

**Comment by cameron1024** [comment]
I'll wait for his answer, but the last time master was passing CI was May 16: https://github.com/input-output-hk/vit-testing/commits/main

**Comment by dkijania** [comment]
We are working on stability of tests for vit-testing. Currently all tests except from `test-debug`  job should pass (and all jobs should compile correctly)

**Comment by cameron1024** [comment]
Will backport to monorepo

**Pull request closed without merging**
